### ISSUE TITLE
Somes themes not working 

### ISSUE THREAD

**Issue by Siddpawar9222** [KevzPeter/Leetcode-Badge-Showcase#10]
Hello, listed themes not working, only light and dark working . Pls fix it . Also add dark black theme, it would be beneficial 🙏.

**Comment by KevzPeter** [comment]
Could you list the themes that aren't working ? I can see all of them are working just fine on the repository's README page.

Sure, we can add a new theme. Can you provide the hex values of the colors you'd like to use for the theme?

**Comment by Siddpawar9222** [comment]
In my case only light and dark where working . Never mind . my bad I am new in this that's why it might happened . Sorry for misunderstanding.  
I would like use dark black theme and hex value is #000000 .

**Comment by KevzPeter** [comment]
I've added a black theme. Here's an example:

![black](https://leetcode-badge-showcase.vercel.app/api?username=kevzpeter&theme=black&filter=study)

If you'd like to change the color scheme, feel free to update the corresponding theme in _utils/themes.json_ file and raise a PR

**Comment by Siddpawar9222** [comment]
Sure 😊. Thank you so much 🙏
