### ISSUE TITLE
When the username is too long, the firstline of the LeetCode Badges appear misaligned

### ISSUE THREAD

**Issue by Flowers2Algernon** [KevzPeter/Leetcode-Badge-Showcase#12]
## What happened?
When the username is too long, the firstline of the LeetCode Badges appear misaligned

## What did you expect to happen?
the firstline of the LeetCode Badges should appear align

## How can we reproduce it (as minimally and precisely as possible)?
input username contains more than 15 characters

## Anything else we need to know?
I have uploaded a screen for this
<img width="274" alt="May15LeetCodeBadgeIssue" src="https://github.com/KevzPeter/Leetcode-Badge-Showcase/assets/139559460/cc98a4a1-c070-486c-9d18-fb0e6d2aa7e0">

**Comment by KevzPeter** [comment]
Hi @Flowers2Algernon 

I've updated the css, it should now appear like this (btw, this is the longest possible username - 30 chars)

![image](https://github.com/KevzPeter/Leetcode-Badge-Showcase/assets/29401940/0cc4372a-0421-453a-adc9-00498b0994c7)

Let me know if any changes are required!

**Comment by Flowers2Algernon** [comment]
Good job bro, its now work fine.
