### ISSUE TITLE
Feature: Add Option to Include/Exclude Outer Border

### ISSUE THREAD

**Issue by shah-zeel** [KevzPeter/Leetcode-Badge-Showcase#8]

**Comment by KevzPeter** [comment]
@shah-zeel , are you referring to the outer border or the border for the header section ?

**Comment by shah-zeel** [comment]
The outer border, my bad, I should have been more descriptive. 
It's going to be my first pull request and first contribution to an Open source project, so just created a pull request. 🥳

**Comment by shah-zeel** [comment]
Hey @KevzPeter
I tried to create a pull request but it failed saying: 
```
Vercel — Authorization required to deploy.
Merging is blocked
Missing successful Preview – leetcode-badge-showcase and Production – leetcode-badge-showcase deployments.
```

Could you please guide me through this?

**Comment by KevzPeter** [comment]
That's because auto-deployment of pull requests to this repository are blocked by default on Vercel (that's where the site is hosted).
I've reviewed your changes and accepted your pull request.

You can view your merged changes on the demo site!
